# Generated by Django 3.2.6 on 2022-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='NoName', max_length=40, verbose_name='Писатель'),
        ),
    ]
